_target_: diffusion_policy.workspace.train_diffusion_unet_lowdim_workspace.TrainDiffusionUnetLowdimWorkspace
action_dim: ${task.action_dim}
checkpoint:
  save_last_ckpt: true
  save_last_snapshot: false
  topk:
    format_str: diffusion_unet.ckpt
    k: 5
    mode: max
    monitor_key: test_mean_score
dataloader:
  batch_size: 256
  num_workers: 1
  persistent_workers: false
  pin_memory: true
  shuffle: true
defaults:
- _self_
- task: pusht_lowdim
ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  inv_gamma: 1.0
  max_value: 0.9999
  min_value: 0.0
  power: 0.75
  update_after_step: 0
exp_name: default
horizon: 16
hydra:
  job:
    override_dirname: ${name}
  run:
    dir: /home/luca_daniel/tum-adlr-04/data/outputs/hparams_7/
  sweep:
    dir: /home/luca_daniel/tum-adlr-04/data/outputs/hparams_7/
    subdir: ${hydra.job.num}
keypoint_dim: ${task.keypoint_dim}
keypoint_visible_rate: 1.0
logging:
  group: null
  id: null
  mode: online
  name: unet
  project: diffusion_policy_debug
  resume: true
  tags:
  - ${name}
  - ${task_name}
  - ${exp_name}
multi_run:
  run_dir: /home/luca_daniel/tum-adlr-04/data/outputs/hparams_7/
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}
n_action_steps: 7
n_latency_steps: 0
n_obs_steps: 6
name: train_diffusion_unet_lowdim
obs_as_global_cond: true
obs_as_local_cond: false
obs_dim: ${task.obs_dim}
optimizer:
  _target_: torch.optim.AdamW
  betas:
  - 0.95
  - 0.999
  eps: 1.0e-08
  lr: 0.0001
  weight_decay: 1.0e-06
past_action_visible: false
policy:
  _target_: diffusion_policy.policy.diffusion_unet_lowdim_policy.DiffusionUnetLowdimPolicy
  action_dim: ${action_dim}
  horizon: ${horizon}
  model:
    _target_: diffusion_policy.model.diffusion.conditional_unet1d.ConditionalUnet1D
    cond_predict_scale: true
    diffusion_step_embed_dim: 256
    down_dims:
    - 256
    - 512
    - 1024
    global_cond_dim: '${eval: ${task.obs_dim}*${n_obs_steps} if ${obs_as_global_cond}
      else None}'
    input_dim: '${eval: ${task.action_dim} if ${obs_as_local_cond} or ${obs_as_global_cond}
      else ${task.obs_dim} + ${task.action_dim}}'
    kernel_size: 5
    local_cond_dim: '${eval: ${task.obs_dim} if ${obs_as_local_cond} else None}'
    n_groups: 8
  n_action_steps: ${eval:'${n_action_steps}+${n_latency_steps}'}
  n_obs_steps: ${n_obs_steps}
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    beta_start: 0.0001
    clip_sample: true
    num_train_timesteps: 100
    prediction_type: epsilon
    variance_type: fixed_small
  num_inference_steps: 100
  oa_step_convention: true
  obs_as_global_cond: ${obs_as_global_cond}
  obs_as_local_cond: ${obs_as_local_cond}
  obs_dim: ${obs_dim}
  pred_action_steps_only: ${pred_action_steps_only}
pred_action_steps_only: false
task_name: ${task.name}
training:
  checkpoint_every: 10
  debug: false
  device: cuda:0
  gradient_accumulate_every: 1
  lr_scheduler: cosine
  lr_warmup_steps: 500
  max_train_steps: null
  max_val_steps: null
  num_epochs: 100
  resume: true
  rollout_every: 20
  sample_every: 5
  seed: 42
  tqdm_interval_sec: 1.0
  use_ema: true
  val_every: 20
val_dataloader:
  batch_size: 256
  num_workers: 1
  persistent_workers: false
  pin_memory: true
  shuffle: false
