wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.18
    start_time: 1731149596.101343
    t:
      1:
      - 50
      - 55
      2:
      - 50
      - 55
      3:
      - 2
      - 13
      - 15
      - 16
      - 23
      4: 3.9.18
      5: 0.13.3
      8:
      - 1
      - 5
